language: node_js
sudo: false
addons:
  code_climate:
    repo_token: 'ac88c25408c831f81cf3f39a32b8fa273546e8ee4c76be309430eced69c134e0'
install:
  - "npm install"
script:
  - "npm run travis"
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
cache:
  directories:
    - 'node_modules'
